// Code generated by "stringer -type=Enum"; DO NOT EDIT.

package VMState

import "fmt"

const _Enum_name = "STOPPEDSTARTINGSTARTEDSTOPPINGERROR"

var _Enum_index = [...]uint8{0, 7, 15, 22, 30, 35}

func (i Enum) String() string {
	if i < 0 || i >= Enum(len(_Enum_index)-1) {
		return fmt.Sprintf("Enum(%d)", i)
	}
	return _Enum_name[_Enum_index[i]:_Enum_index[i+1]]
}
