#
# Copyright 2018, CS Systemes d'Information, http://www.c-s.fr
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
feature:
    name: OpenHPC Slurm Node
    suitableFor:
        host: yes
        cluster: ohpc
    install:
        bash:
            wallTime: 15
            check: |
                rpm -qa | grep ohpc-slurm-server &>/dev/null

            add: |
                yum install -y http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/x86_64/ohpc-release-1.3-1.el7.x86_64.rpm && \
                yum install -y ohpc-base-compute ohpc-slurm-client lmod-ohpc ganglia-gmond-ohpc nhc-ohpc && \
                yum install -y ohpc-autotools EasyBuild-ohpc hwloc-ohpc spack-ohpc valgrind-ohpc && \
                yum install -y openmpi3-gnu7-ohpc mpich-gnu7-ohpc  ohpc-gnu7-perf-tools slurm-torque || exit $?
                sed -i -e 's/ControlMachine=.*$/ControlMachine={{.PrimaryMasterName}}/g' /etc/slurm/slurm.conf
                sed -e 's/<sms>/{{.PrimaryMasterIP}}/g' /opt/ohpc/pub/examples/ganglia/gmond.conf >/etc/ganglia/gmond.conf
                systemctl enable slurmd
                systemctl enable gmond
                systemctl start slurmd
                systemctl start gmond

            remove: |
                yum install -y ohpc-base-compute ohpc-slurm-client lmod-ohpc ganglia-gmond-ohpc nhc-ohpc \
                               ohpc-autotools EasyBuild-ohpc hwloc-ohpc spack-ohpc valgrind-ohpc \
                               openmpi3-gnu7-ohpc mpich-gnu7-ohpc ohpc-gnu7-perf-tools slurm-torque

    service:
        start: |
            systemctl start slurm-server

        stop: |
            systemctl stop slurm-server

        state: |
            systemctl status slurm-server

...