apiVersion: v1
kind: Namespace
metadata:
  name: csi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-psp-csi-serviceaccounts
roleRef:
  kind: ClusterRole
  name: privileged-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group 
  name: system:serviceaccounts 
  apiGroup: rbac.authorization.k8s.io 
  namespace: csi