// Code generated by "stringer -type=Enum"; DO NOT EDIT.

package IPVersion

import "fmt"

const (
	_Enum_name_0 = "IPv4"
	_Enum_name_1 = "IPv6"
)

var (
	_Enum_index_0 = [...]uint8{0, 4}
	_Enum_index_1 = [...]uint8{0, 4}
)

func (i Enum) String() string {
	switch {
	case i == 4:
		return _Enum_name_0
	case i == 6:
		return _Enum_name_1
	default:
		return fmt.Sprintf("Enum(%d)", i)
	}
}
