#!/bin/sh

if [ "$NO_VERIFY" ]; then
    echo 'pre-commit hook skipped' 1>&2
    exit 0
fi

if [ -x ./git-hooks-env ]; then
    . ./git-hooks-env
fi

# Make sure format and build are OK
make gofmt checkbuild
RESULT=$?

[ $RESULT -ne 0 ] && exit 1

# Run UT before commit
make precommittest
RESULT=$?

[ $RESULT -ne 0 ] && exit 1

exit 0
