// Code generated by "stringer -type=Enum"; DO NOT EDIT.

package Complexity

import "strconv"

const (
	_Enum_name_0 = "Dev"
	_Enum_name_1 = "HighAvailability"
	_Enum_name_2 = "HighVolume"
)

func (i Enum) String() string {
	switch {
	case i == 1:
		return _Enum_name_0
	case i == 3:
		return _Enum_name_1
	case i == 5:
		return _Enum_name_2
	default:
		return "Enum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
