name: MacOs Go Build CI

on:
  push:
    branches:
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'

env:
  PROTOCVERSION: 3.17.3

jobs:

  build-macos:

    strategy:
      matrix:
        go: [ 1.16.15, 1.17.8, 1.18 ]
        tags: [ releasetags, tunnel ]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Install Protoc
      run: |
        brew update
        brew install protoc-gen-go
        brew install md5sha1sum

    - run: make ${{ matrix.tags }} rawci with-coverage
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: macos-artefacts
        path: |
          generation_results.log
          vet_results.log
          test_results.log
          style_results.log
          semgrep_results.log
          go.mod
          go.sum
