name: licenses

on:
  push:
    branches:
      - hotfixes
      - master
      - develop
      - 'review/**'

env:
  GOVERSION: '1.16.8' # The Go version to download (if necessary) and use.
  PROTOCVERSION: 3.17.3

jobs:

  build-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{env.GOVERSION}}
      - name: Install Protoc
        run: |
          cd /tmp
          PROTOCZIP=$(echo "protoc-${{env.PROTOCVERSION}}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m).zip")
          wget https://github.com/google/protobuf/releases/download/v${{env.PROTOCVERSION}}/$PROTOCZIP
          sudo unzip -d /opt/protoc $PROTOCZIP
          sudo chmod a+r -R /opt/protoc
          sudo chmod a+xr /opt/protoc/bin/protoc
          sudo ln -s /opt/protoc/bin/protoc /usr/local/bin/
      - run: make rawci
      - uses: oscarpicas/go-mod-license-checker@v0.4.8
        with:
          goversion: ${{env.GOVERSION}}

      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: linux-build-info
          path: |
            go.mod
            go.sum
            licenses.csv
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: linux-artefacts
          path: |
            generation_results.log
            vet_results.log
            test_results.log
            style_results.log
            semgrep_results.log
            go.mod
            go.sum
            licenses.csv
