name: Release

on:
  push:
    tags:
      - "v*"

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - id: get_version
      uses: battila7/get-version-action@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.5' # The Go version to download (if necessary) and use.

    - name: Install Protoc
      run: |
        cd /tmp
        PROTOCVERSION=3.17.3
        PROTOCZIP=$(echo "protoc-${PROTOCVERSION}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m).zip")
        wget https://github.com/google/protobuf/releases/download/v${PROTOCVERSION}/$PROTOCZIP
        sudo unzip -d /opt/protoc $PROTOCZIP
        sudo chmod a+r -R /opt/protoc
        sudo chmod a+xr /opt/protoc/bin/protoc
        sudo ln -s /opt/protoc/bin/protoc /usr/local/bin/

    - name: Make Release
      run: make release
      env:
        VERSION: ${{ steps.get_version.outputs.version-without-v }}

    - name: Publish Release
      uses: softprops/action-gh-release@v1
      with:
        name: SafeScale ${{ steps.get_version.outputs.version }}
        prerelease: ${{ contains(steps.get_version.outputs.version, '-rc') }}
        files: |
          safescale-${{ steps.get_version.outputs.version }}*
          